### ISSUE TITLE
Cheese RV - M3406-ADJ, please replace with MT9216

### ISSUE THREAD

**Issue by ShirBlackspots** [Sorakage033/SlimeVR-CheeseCake#16]
JCLPCB does not have a large inventory of the M3406-ADJ.  It has a unique pin out compared to other similar chips, such as the MT9216.  Could the PCB be revised to use the MT9216, which JCLPCB has a large inventory of (both have the same specs, just different pinout)

Traces using the XI'AN Aerosemi Tech M3406-ADJ
![Screenshot 2024-09-21 171401](https://github.com/user-attachments/assets/31d1631e-788d-4a38-8b03-b2cda5146a70)

Traces using the XI'AN Aerosemi Tech MT9216
![Screenshot 2024-09-21 171517](https://github.com/user-attachments/assets/6479eee6-e57d-45f2-a65d-d5d8ce703278)
The Shouding SD8916A will also work in its place

I do not know how to properly export this so JCLPCB sees it correctly.

Also, JCLPCB does not have inventory of the inductor APV APH252010T2R2M.  It can be safely replaced with FH (Guangdong Fenghua Advanced Tech) PIM252010-2R2MTS00, which has the same specs

**Comment by Sorakage033** [comment]
You can use TI's TLV62569DBVR (C141836) instead, they are pin-to-pin compatible.

**Comment by ShirBlackspots** [comment]
Thank you very much!
